linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  gosimple:
    checks: ["all"]
  staticcheck:
    checks: ["all"]
  unused:
    check-exported: false
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/yash/transaction-system

linters:
  enable:
    - errcheck
    - govet
    - gofmt
    - goimports
    - typecheck
  disable:
    - gochecknoglobals  # Allow global metrics
    - gochecknoinits    # Allow init functions if needed
    - gocritic          # Too strict for this project
    - gosec             # Security checks can be noisy
    - gosimple          # Can be too strict
    - staticcheck       # Can be too strict
    - ineffassign       # Can be too strict
    - unused            # Can flag legitimate code
    - misspell          # Can be noisy

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - linters:
        - errcheck
      text: "Error return value of .* is not checked"
      source: "^\\s*defer .*"
    - linters:
        - errcheck
      text: "Error return value of .* is not checked"
      source: "^\\s*_, _ ="

